test_objet:initobjet.o afficherobjet.o main.o
	gcc initobjet.o afficherobjet.o  main.o -o prog
main.o:main.c
	gcc -c main.c
initobjet.o:initobjet.o
	gcc -c initobjet.c
afficherobjet.o:afficherobjet.o
	gcc -c afficherobjet.c
